-- Settings.lua
-- Tiny disk-backed persistence for player-facing preferences that must survive
-- between sessions. Currently only the tutorial toggle. Values are mirrored into
-- Config at load time so the rest of the game keeps reading Config as before.
-- Stored via love.filesystem in the LOVE save directory (works on web too, where
-- love.js backs the save dir with IndexedDB).

local Config = require("src.Config")

local Settings = {}

local FILE = "settings.lua"

-- Read settings.lua (if present) and mirror known keys into Config.
function Settings.load()
    if not (love and love.filesystem and love.filesystem.getInfo(FILE)) then
        return
    end

    local chunk = love.filesystem.load(FILE)
    if not chunk then return end

    local ok, data = pcall(chunk)
    if not ok or type(data) ~= "table" then
        print("[Settings] Ignoring corrupt settings file")
        return
    end

    if type(data.tutorialEnabled) == "boolean" then
        Config.gameplay.tutorialEnabled = data.tutorialEnabled
    end

    print("[Settings] Loaded (tutorialEnabled=" .. tostring(Config.gameplay.tutorialEnabled) .. ")")
end

-- Serialize the persisted subset of Config back to disk.
function Settings.save()
    if not (love and love.filesystem) then return end

    local serialized = string.format(
        "-- Auto-generated by Settings.save(); edit in-game via Options > GAMEPLAY\nreturn {\n    tutorialEnabled = %s,\n}\n",
        tostring(Config.gameplay.tutorialEnabled)
    )

    local ok, err = pcall(love.filesystem.write, FILE, serialized)
    if not ok then
        print("[Settings] Failed to save: " .. tostring(err))
    end
end

return Settings
